sample_update
Padma-Prabhu-Raki/ClgExhibition-Training-Project pull request #1
Opened 2022-12-09 04:46 UTC by Padma-Prabhu-Raki

2022-12-09 07:47 UTC, Sushmitha-Vk requested changes

2022-12-09 07:47 UTC, Sushmitha-Vk commented on src/app/app-routing.module.ts
> +        path : ':/Hardware ',
why was this / added..? and remove the space after Hardware, it will consider space also in url

2022-12-09 07:47 UTC, Sushmitha-Vk commented on src/app/cards-topicsexhibitions/cards-topicsexhibitions.component.ts
> -        return cardData;
wrong way of implementing, do as i have suggested today

2022-12-12 18:30 UTC, Sushmitha-Vk requested changes

2022-12-12 18:30 UTC, Sushmitha-Vk commented on src/app/cards-topicsexhibitions/cards-topicsexhibitions.component.ts
> +    console.log('---', routenavurl);
console.log

2022-12-12 18:30 UTC, Sushmitha-Vk commented on src/app/cards-topicsexhibitions/cards-topicsexhibitions.component.ts
> +  // if(this.route.url.includes('cards-exhibitions')){
remove commented codes

2022-12-12 18:30 UTC, Sushmitha-Vk commented on src/app/stepper-selector/stepper-selector.component.ts
>                                        // console.log('------', submittingStudentData)
remove all commented codes

2022-12-13 07:31 UTC, Padma-Prabhu-Raki commented on src/app/cards-topicsexhibitions/cards-topicsexhibitions.component.ts
> +    console.log('---', routenavurl);
resolved this, mam

2022-12-14 05:47 UTC, Sushmitha-Vk requested changes

2022-12-14 05:47 UTC, Sushmitha-Vk commented on src/app/add-newstudent/add-newstudent.component.ts
>        // console.log("---d---",editStudentData)
console

2022-12-14 05:47 UTC, Sushmitha-Vk commented on src/app/app-routing.module.ts
> +        // redirectTo : '/Conference',
remove comments

2022-12-14 05:47 UTC, Sushmitha-Vk commented on src/app/card-routing/card-routing.component.ts
>        // console.log('---------',getStudentById)
comments

2022-12-14 05:47 UTC, Sushmitha-Vk commented on src/app/cards-topicsexhibitions/cards-topicsexhibitions.component.ts
> +  //  }
comments

2022-12-14 05:47 UTC, Sushmitha-Vk commented on src/app/editdashboard/editdashboard.component.ts
>        // console.log('---------',getStudentById)
comments

2022-12-14 05:47 UTC, Sushmitha-Vk commented on src/app/headerdashboard/headerdashboard.component.ts
> +    // window.location.reload();
comments

2022-12-14 05:47 UTC, Sushmitha-Vk commented on src/app/stepper-selector/stepper-selector.component.ts
>        // console.log("------",updateStudentData)
comments

2022-12-14 08:54 UTC, Sushmitha-Vk approved these changes

2022-12-14 09:05 UTC, merged